component_depth: 1
languages:
- javascript
- typescript

exclude:
- /purplepension-frontend/src/karma\.conf\.js
- /purplepension-frontend/e2e/protractor\.conf\.js
- /purplepension-backend/api/controllers/activity\.activity_events\.js
- /purplepension-frontend/src/app\.app-routing.module\.ts